@startuml
' skinparam linetype ortho
left to right direction

entity "approval" as APV {
    name                    : string    {not null}
    description             : string    {nullable}
    related_object_category : enum      {not null, default: document, index}
    action_type             : enum      {default: create, index}
    final_status            : enum      {not null, default: pending}
    signers                 : jsonb     {not null}
    delay_count             : integer   {default: 0}
    created_time            : datetime  {not null, default: now() }
    --
    id                      : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    uploadfile_entity_id    : UUID      <<FK>>  {not null, references uploadfile_entity(id)}
    related_object_id       : UUID      <<FK>>  {not null, index, references announcement(id) when related_object_category='announcement'}
}

entity "risk_control" as RSC {
    name                    : string     {not null}
    description             : text       {not null}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    parent_id               : UUID       <<FK>> {references risk_control(id)}
}
RSC ||--o{ RSC : children
RSC ||--o{ APV : approvals

entity "risk" as RSK {
    final_state             : enum risk_processing_state {not null, default: 'unprocessed'} <index>
    treatment_strategy      : enum risk_treatment_strategy {nullable} <index>
    original_value          : float      {not null}
    final_value             : integer    {nullable}
    reduce_value            : integer    {nullable}
    is_trackable            : bool       {not null, default: false}
    tracking_interval_days  : integer    {nullable}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    asset_id                : UUID       <<FK>> {not null, references asset(id)}
    threat_id               : UUID       <<FK>> {not null, references threat(id)}
    vulnerability_id        : UUID       <<FK>> {not null, references vulnerability(id)}
    parent_id               : UUID       <<FK>> {references risk(id)}
}
RSK ||--o{ RSK : children
RSK ||--o{ APV : approvals

entity "role" as ROL {
    name                  : string    {not null}
    description           : text      {not null}
    is_temp               : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references role(id)}
}
ROL ||--o{ ROL : children
ROL ||--o{ APV : approvals

entity "user" as USR {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    account               : string    {not null}
    username              : string    {not null}
    session_start_time    : datetime  {nullable}
    session_end_time      : datetime  {nullable}
    is_active             : bool      {not null, default: true}
    is_temp               : bool      {not null, default: false}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    role_id               : UUID      <<FK>>  {not null, references role(id)}
    parent_id             : UUID      <<FK>>  {references user(id)}
}
USR ||--o{ USR : children
USR ||--o{ APV : approvals

entity "audit_title" as AUT {
    name          : string(255)  {not null}
    description   : text         {nullable}
    created_time  : datetime     {not null, default: now()}
    version_group_id : string    {not null}
    is_current    : bool         {not null, default: false}
    --
    id            : UUID         <<PK>> {not null, default: uuid_generate_v4()}
}
AUT ||--o{ AUT : children
AUT ||--o{ APV : approvals
@enduml
