@startuml
' skinparam linetype ortho
left to right direction

entity "approval" as APV {
    name                    : string    {not null}
    description             : string    {nullable}
    related_object_category : enum      {not null, default: document, index}
    action_type             : enum      {default: create, index}
    final_status            : enum      {not null, default: pending}
    signers                 : jsonb     {not null}
    delay_count             : integer   {default: 0}
    created_time            : datetime  {not null, default: now() }
    --
    id                      : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    uploadfile_entity_id    : UUID      <<FK>>  {not null, references uploadfile_entity(id)}
    related_object_id       : UUID      <<FK>>  {not null, index, references announcement(id) when related_object_category='announcement'}
}





entity "vulnerability" as VUL {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    value                           : float     {not null}
    type                            : CiaType   {not null}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references vulnerability(id)}
}
VUL ||--o{ VUL : children
VUL ||--o{ APV : approvals

entity "risk_control" as RSC {
    version_group_id  : string    {not null}
    is_current        : bool      {not null, default: false}
    created_time      : datetime  {not null, default: now() }
    name              : string    {not null}
    description       : string    {not null}
    --
    id                : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    risk_id           : UUID      <<FK>>  {not null, references risk(id)}
    parent_id         : UUID      <<FK>>  {references risk_control(id)}
}
RSC ||--o{ RSC : children
RSC ||--o{ APV : approvals

entity "risk" as RSK {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    value                 : float     {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    asset_id              : UUID      <<FK>>  {not null, references asset(id)}
    threat_id             : UUID      <<FK>>  {not null, references threat(id)}
    vulnerability_id      : UUID      <<FK>>  {not null, references vulnerability(id)}
    parent_id             : UUID      <<FK>>  {references risk(id)}
}
RSK ||--o{ RSK : children
RSK ||--o{ APV : approvals

entity "role" as ROL {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    name                  : string    {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references role(id)}
}
ROL ||--o{ ROL : children
ROL ||--o{ APV : approvals

entity "user" as USR {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    account               : string    {not null}
    username              : string    {not null}
    session_start_time    : datetime  {nullable}
    session_end_time      : datetime  {nullable}
    is_active             : bool      {not null, default: true}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references user(id)}
}
USR ||--o{ USR : children
USR ||--o{ APV : approvals
@enduml

@enduml
