@startuml backend-package
package "Backend" as BE {
  package "app" as APP {
    package "adapters" as AD {
      package "inbound.api.endpoints" as IAE
      package "outbound" as OUT
    }
    package "application" as APPLICATION
    package "domain" as DOM
    package "framework" as FR
  }
  package "tests" as TS
}
@enduml
