@startuml monitoring-package
package "Monitoring" as MON {
  package "grafana" as GRAFANA {
    artifact "default.yaml" as GRAFANA_CFG
  }
  package "loki" as LOKI {
    artifact "loki-config.yaml" as LOKI_CFG
    artifact "config.alloy" as ALLOY_CFG
  }
  package "prometheus" as PROM {
    artifact "prometheus.yml" as PROM_CFG
  }
}
@enduml
