@startuml

package "Kubernetes Cluster" {

  package "Network Layer" {
    [Ingress Controller\n(ingress-nginx)] as Ingress
  }

  package "Application" {
    package "Presentation" {
      [Frontend\n(React, TS, PWA)] as Frontend
    }
    package "Business Logic" {
      [Backend\n(Python, FastAPI)] as Backend
      [Consumer\n(Python Worker)] as Consumer
      [AI Module\n(Embedding & RAG)] as AIModule
    }
  }

  package "Data Services" {
    [RabbitMQ\n(Message Broker)] as RabbitMQ
    [MinIO\n(Object Storage)] as MinIO
    [PostgreSQL\n(SQLAlchemy, Alembic)] as Database
  }
}

package "External" {
  [Google SMTP Server] as SMTP
}

' Define dependencies between packages
Ingres-->Frontend : HTTP/HTTPS
Frontend-->Backend : REST API
Backend-->RabbitMQ : AMQP
Consumer-->RabbitMQ : AMQP
Backend-->MinIO : S3 API
Backend-->Database : TCP:5432
Backend-->AIModule : prompts & data
AIModule-->Database : embeddings & RAG
AIModule-->SMTP : email
@enduml
