@startuml scheduler-package
package "Scheduler" as SCH {
  package "app" as SCH_APP {
    package "adapter" as SCH_AD
    package "domain" as SCH_DOM {
      package "value_objects" as SCH_VO
    }
    package "infrastructure" as SCH_INFRA {
      package "core" as SCH_CORE
      package "security" as SCH_SEC
      package "scheduler" as SCH_SCHED
      package "email_template" as SCH_EMAIL
    }
    package "repositories" as SCH_REPO
    package "services" as SCH_SVC {
      package "notification" as SCH_NOTIF
      package "expired" as SCH_EXP
    }
    package "utils" as SCH_UTILS
  }
}
@enduml
