@startuml
node "Browser" 

node "Kubernetes Cluster" <<Cluster>> {
  package "Ingress-Controller Namespace" <<Namespace>> {
    node "ingress-nginx" <<Pod>> as IngressController {
      component "nginx Ingress Controller"
    }
  }
  package "ntub-secumanage Namespace" <<Namespace>> {
    node "frontend-pod" <<Pod>> as FE {
      component "nginx"
      artifact "dist/\n(static files)"
    }
    node "backend-pod" <<Pod>> as BE {
      component "Python App"
    }
    node "postgresql-pod" <<Pod>> as DB {
      database "PostgreSQL\n(TCP:5432)"
    }
    node "minio-pod" <<Pod>> as S3 {
      storage "MinIO\n(S3 API)"
    }
    node "rabbitmq-pod" <<Pod>> as RMQ {
      component "RabbitMQ\n(AMQP)"
    }
  }
}

Browser --> IngressController : HTTP/HTTPS
IngressController --> FE   : HTTP/HTTPS (load-balancing)
FE               --> BE   : REST API
BE               --> DB   : TCP:5432
BE               --> S3   : S3 API
BE               --> RMQ  : AMQP
@enduml