@startuml
actor Reviewer as "簽核者"

participant Frontend
participant Backend
participant Database
participant RabbitMQ
actor User as "申請者"

Reviewer ->> Frontend: 點選「拒絕」
Frontend ->> Backend: POST /api/system/approval/{approval_id}/user/{user_id}/rejected
Backend ->> Backend: 驗證簽核事件
Backend ->> Database: 更新簽核資料
Backend ->> RabbitMQ: 發送拒絕訊息到 RabbitMQ Reject Queue
RabbitMQ ->> Database: 處理拒絕資料的副作用
Backend -->> Frontend: 回傳成功訊息
RabbitMQ -->> User: 發送拒絕通知

@enduml