@startuml asset_category_overview

left to right direction

actor 使用者

package "資產分類" {
    usecase "檢查權限" as UC12
    usecase "瀏覽資產分類列表" as UC1
    usecase "檢視資產分類欄位（ID、名稱、描述、狀態）" as UC2
    usecase "選擇每頁顯示筆數" as UC3
    usecase "搜尋資產分類資料" as UC4
    usecase "修改分類資料" as UC5
    usecase "刪除分類資料" as UC6
    usecase "＋新增資產類別" as UC7
    usecase "＋匯入資產類別" as UC8
    usecase "匯入資產類別後自動創建核准項目" as UC10
    usecase "手動核准項目" as UC11
}

使用者 --> UC12
UC12 .down.> UC1 : <<include>>
UC12 .down.> UC5 : <<include>>
UC12 .down.> UC6 : <<include>>
UC12 .down.> UC7 : <<include>>
UC12 .down.> UC8 : <<include>>
UC12 .down.> UC10 : <<include>>

UC1 .down.> UC4 : <<include>>
UC5 .down.> UC11 : <<include>>
UC6 .down.> UC11 : <<include>>
UC7 .down.> UC11 : <<include>>
UC8 .down.> UC10 : <<include>>

@enduml
