@startuml

class alembic_version {
  varchar(32) version_num
}
class announcement {
  varchar version_group_id
  boolean is_current
  timestamp with time zone date
  varchar title
  varchar description
  boolean is_show
  uuid parent_id
  uuid id
  + get_announcement_version_record()
  + get_paginated_announcement_with_status()
  + create_announcement()
  + validation_and_update_announcement()
  + validation_and_delete_announcement()
}
class app_setting {
  varchar version_group_id
  boolean is_current
  uuid uploadfile_entity_id
  uuid parent_id
  uuid id
  + get_app_setting()
  + get_app_setting_version_record()
  + create_app_setting()
}
class approval {
  varchar name
  uuid related_object_id
  related_object_category related_object_category
  action_type action_type
  approval_status final_status
  jsonb signers
  integer delay_count
  timestamp with time zone created_at
  uuid uploadfile_entity_id
  uuid id
  + get_approval()
  + get_paginated_approval_with_status()
  + get_paginated_approval_with_status_for_user()
  + get_approval_with_document_path()
  + create_approval()
  + update_approval()
  + delete_approval()
  # _publish_queue_and_send_mail()
  # _build_and_save()
  # _get_signer_pending_user()
  # _get_valid_generate_presigned_url()
  # _translate_submit()
  # _translate_email_approval()
  # _translate_email_user()
}
class asset {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  jsonb custom_fields
  uuid asset_category_id
  uuid parent_id
  uuid id
  + get_asset()
  + get_asset_with_category()
  + get_asset_version_record()
  + get_paginated_asset_with_status()
  + create_asset()
  + validation_and_update_asset()
}
class asset_category {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  uuid parent_id
  uuid id
  + get_asset_category()
  + get_assets_by_category()
  + get_asset_category_version_record()
  + get_pagination_asset_category_with_status()
  + get_asset_catgory_dropdown()
  + create_asset_category()
  + validation_and_update_asset_category()
  + validation_and_delete_asset_category()
  + get_asset_category_statistics()
}
class asset_setting {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision high_risk
  double precision medium_risk
  double precision low_risk
  varchar calculation_formula
  varchar calculation_formula_description
  jsonb custom_fields
  uuid parent_id
  uuid id
  + get_asset_setting()
  + get_asset_setting_version_record()
  + get_asset_setting_custom_fields()
  + validation_and_update_asset_setting()
}
class assignment {
  varchar description
  timestamp with time zone start_date
  timestamp with time zone end_date
  varchar manager
  varchar job_name
  integer id
  + create_assignment()
  + update_assignment()
  + delete_assignment()
}
class document {
  varchar version_group_id
  boolean is_current
  integer level
  varchar name
  timestamp with time zone created_date
  uuid uploadfile_entity_id
  uuid creator_id
  uuid parent_id
  uuid id
  + create_document()
  + get_document()
  + get_document_version_record()
  + get_paginated_document_with_status()
  + create_document_command_from_approval()
  + archive_document()
  + process_document_archive_if_needed()
  # _get_valid_uploadfile_entity()
  # _get_valid_generate_presigned_url()
  # _build_document_entity()
}
class formula_variable {
  varchar name
  varchar description
  double precision value
  uuid asset_setting_id
  integer id
}
class permission {
  varchar name
  integer id
}
class risk {
  varchar version_group_id
  boolean is_current
  double precision value
  uuid asset_id
  uuid threat_id
  uuid vulnerability_id
  uuid parent_id
  uuid id
  + get_risk()
  + get_risk_version_record()
  + get_paginated_risk_with_status()
  + get_risk_top_5()
  + create_risk()
  + validation_and_update_risk()
  + validation_and_delete_risk()
  + get_risk_level_statistics()
}
class role {
  varchar version_group_id
  boolean is_current
  varchar name
  uuid parent_id
  uuid id
  + get_role()
  + get_role_version_record()
  + get_paginated_role_with_status()
  + get_user_dropdown_by_role_id()
  + get_role_dropdown()
  + create_role()
  + validation_and_update_role()
  + validation_and_delete_role()
}
class role_permission_link {
  uuid role_id
  integer permission_id
}
class threat {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  cia_type type
  uuid parent_id
  uuid id
  + get_threat()
  + get_threat_version_record()
  + get_paginated_threat_with_status()
  + get_threat_dropdown()
  + create_threat()
  + create_multiple_instances()
  + validation_and_update_threat()
  + validation_and_delete_threat()
}
class uploadfile_entity {
  varchar name
  varchar path
  uuid id
  + get_uploadfile_entity()
  + create_uploadfile_entity()
}
class user {
  varchar version_group_id
  boolean is_current
  varchar account
  varchar username
  timestamp with time zone session_start_time
  timestamp with time zone session_end_time
  boolean is_active
  uuid parent_id
  uuid id
  + get_user_dropdown()
  + get_user_version_record()
  + get_paginated_user_with_status()
  + get_user_with_permisssion()
  + create_user()
  + validation_and_update_user()
  + validation_and_delete_user()
}
class user_permission_link {
  uuid user_id
  integer permission_id
}
class user_role_link {
  uuid user_id
  uuid role_id
}
class vulnerability {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  cia_type type
  uuid parent_id
  uuid id
  + get_vulnerability()
  + get_vulnerability_version_record()
  + get_paginated_vuln_with_status()
  + get_vulnerability_dropdown()
  + parse_xlsx_to_instances()
  + create_vulnerability()
  + create_multiple_instances()
  + validation_and_update_vulnerability()
  + validation_and_delete_vulnerability()
}

announcement --> announcement : parent_id:id
app_setting --> app_setting : parent_id:id
app_setting --> uploadfile_entity : uploadfile_entity_id:id
approval --> uploadfile_entity : uploadfile_entity_id:id
asset --> asset : parent_id:id
asset --> asset_category : asset_category_id:id
asset_category --> asset_category : parent_id:id
asset_setting --> asset_setting : parent_id:id
document --> document : parent_id:id
document --> uploadfile_entity : uploadfile_entity_id:id
document --> user : creator_id:id
formula_variable --> asset_setting : asset_setting_id:id
risk --> asset : asset_id:id
risk --> risk : parent_id:id
risk --> threat : threat_id:id
risk --> vulnerability : vulnerability_id:id
role --> role : parent_id:id
role_permission_link --> permission : permission_id:id
role_permission_link --> role : role_id:id
threat --> threat : parent_id:id
user --> user : parent_id:id
user_permission_link --> permission : permission_id:id
user_permission_link --> user : user_id:id
user_role_link --> role : role_id:id
user_role_link --> user : user_id:id
vulnerability --> vulnerability : parent_id:id
@enduml
