@startuml

left to right direction

class alembic_version {
  varchar(32) version_num
}
class announcement {
  varchar version_group_id
  boolean is_current
  timestamp with time zone date
  varchar title
  varchar description
  boolean is_show
  uuid parent_id
  uuid id
  + void 
}
class app_setting {
  varchar version_group_id
  boolean is_current
  uuid uploadfile_entity_id
  uuid parent_id
  uuid id
}
class approval {
  varchar name
  uuid related_object_id
  related_object_category related_object_category
  action_type action_type
  approval_status final_status
  jsonb signers
  integer delay_count
  timestamp with time zone created_at
  uuid uploadfile_entity_id
  uuid id
}
class asset {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  jsonb custom_fields
  uuid asset_category_id
  uuid parent_id
  uuid id
}
class asset_category {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  uuid parent_id
  uuid id
}
class asset_setting {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision high_risk
  double precision medium_risk
  double precision low_risk
  varchar calculation_formula
  varchar calculation_formula_description
  jsonb custom_fields
  uuid parent_id
  uuid id
}
class assignment {
  varchar description
  timestamp with time zone start_date
  timestamp with time zone end_date
  varchar manager
  varchar job_name
  integer id
}
class document {
  varchar version_group_id
  boolean is_current
  integer level
  varchar name
  timestamp with time zone created_date
  uuid uploadfile_entity_id
  uuid creator_id
  uuid parent_id
  uuid id
}
class formula_variable {
  varchar name
  varchar description
  double precision value
  uuid asset_setting_id
  integer id
}
class permission {
  varchar name
  integer id
}
class risk {
  varchar version_group_id
  boolean is_current
  double precision value
  uuid asset_id
  uuid threat_id
  uuid vulnerability_id
  uuid parent_id
  uuid id
}
class role {
  varchar version_group_id
  boolean is_current
  varchar name
  uuid parent_id
  uuid id
}
class role_permission_link {
  uuid role_id
  integer permission_id
}
class threat {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  cia_type type
  uuid parent_id
  uuid id
}
class uploadfile_entity {
  varchar name
  varchar path
  uuid id
}
class user {
  varchar version_group_id
  boolean is_current
  varchar account
  varchar username
  timestamp with time zone session_start_time
  timestamp with time zone session_end_time
  boolean is_active
  uuid parent_id
  uuid id
}
class user_permission_link {
  uuid user_id
  integer permission_id
}
class user_role_link {
  uuid user_id
  uuid role_id
}
class vulnerability {
  varchar version_group_id
  boolean is_current
  varchar name
  varchar description
  double precision value
  cia_type type
  uuid parent_id
  uuid id
}

announcement --> announcement : parent_id:id
app_setting --> app_setting : parent_id:id
app_setting --> uploadfile_entity : uploadfile_entity_id:id
approval --> uploadfile_entity : uploadfile_entity_id:id
asset --> asset : parent_id:id
asset --> asset_category : asset_category_id:id
asset_category --> asset_category : parent_id:id
asset_setting --> asset_setting : parent_id:id
document --> document : parent_id:id
document --> uploadfile_entity : uploadfile_entity_id:id
document --> user : creator_id:id
formula_variable --> asset_setting : asset_setting_id:id
risk --> asset : asset_id:id
risk --> risk : parent_id:id
risk --> threat : threat_id:id
risk --> vulnerability : vulnerability_id:id
role --> role : parent_id:id
role_permission_link --> permission : permission_id:id
role_permission_link --> role : role_id:id
threat --> threat : parent_id:id
user --> user : parent_id:id
user_permission_link --> permission : permission_id:id
user_permission_link --> user : user_id:id
user_role_link --> role : role_id:id
user_role_link --> user : user_id:id
vulnerability --> vulnerability : parent_id:id
@enduml
