@startuml
' skinparam linetype ortho
left to right direction

entity "approval" as APV {
    name                    : string    {not null}
    description             : string    {nullable}
    related_object_category : enum      {not null, default: document, index}
    action_type             : enum      {default: create, index}
    final_status            : enum      {not null, default: pending}
    signers                 : jsonb     {not null}
    delay_count             : integer   {default: 0}
    created_time            : datetime  {not null, default: now() }
    --
    id                      : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    uploadfile_entity_id    : UUID      <<FK>>  {not null, references uploadfile_entity(id)}
    related_object_id       : UUID      <<FK>>  {not null, index, references announcement(id) when related_object_category='announcement'}
}

enum RelatedObjectCategory {
    ASSET
    APP_SETTING
    ANNOUNCEMENT
    ASSET_CATEGORY
    ASSET_SETTING
    DOCUMENT
    RISK
    RISK_CONTROL
    ROLE
    USER
    THREAT
    VULNERABILITY
    ETC
}

enum ActionType {
    CREATE
    UPDATE
    DELETE
}

enum ApprovalStatus {
    PENDING(待辦中)
    REJECTED(拒絕)
    APPROVED(核准)
}

class SysSigners {
    user_id   : UUID
    status    : ApprovalStatus
    deadline  : datetime
}

APV --> "0..*" SysSigners    : signers
APV ..> RelatedObjectCategory : related_object_category
APV ..> ActionType           : action_type
APV ..> ApprovalStatus       : final_status

note on link
    FK uploadfile_entity_id -> uploadfile_entity.id
    FK announcement.id → approval.related_object_id
    FK asset.id → approval.related_object_id
    FK asset_category.id → approval.related_object_id
    FK asset_setting.id → approval.related_object_id
    FK app_setting.id → approval.related_object_id
    FK document.id → approval.related_object_id
    FK risk.id → approval.related_object_id
    FK risk_control.id → approval.related_object_id
    FK threat.id → approval.related_object_id
    FK vulnerability.id → approval.related_object_id
    FK user.id → approval.related_object_id
    FK role.id → approval.related_object_id
end note

entity "uploadfile_entity" as UPE {
    name : string {not null}
    path : string {not null}
    --
    id   : UUID   <<PK>> {not null, default: uuid_generate_v4()}
}
UPE ||--o{ APV : approvals

entity "announcement" as ANN {
    date              : datetime  {not null}
    version_group_id  : string    {not null}
    title             : string    {not null}
    description       : string    {not null}
    is_show           : bool      {not null}
    is_current        : bool      {not null, default: false}
    created_time      : datetime  {not null, default: now() }
    --
    id                : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id         : UUID      <<FK>>  {references announcement(id)}
}
ANN ||--o{ ANN : children
ANN ||--o{ APV : approvals

entity "asset_category" as ASC {
    version_group_id  : string    {not null}
    is_current        : bool      {not null, default: false}
    created_time      : datetime  {not null, default: now() }
    name              : string    {not null}
    description       : string    {not null}
    --
    id                : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id         : UUID      <<FK>>  {references asset_category(id)}
}
ASC ||--o{ ASC : children
ASC ||--o{ APV : approvals

entity "asset" as AST {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    name                  : string    {not null}
    description           : string    {not null}
    value                 : float     {not null}
    custom_fields         : json      {nullable}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references asset(id)}
    asset_category_id     : UUID      <<FK>>  {not null, references asset_category(id)}
}
AST ||--o{ AST : children
AST ||--o{ APV : approvals

entity "asset_setting" as ASTS {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    high_risk                       : float     {not null}
    medium_risk                     : float     {not null}
    low_risk                        : float     {not null}
    calculation_formula             : string    {nullable}
    calculation_formula_description : string    {nullable}
    custom_fields                   : json      {nullable}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references asset_setting(id)}
}
ASTS ||--o{ ASTS : children
ASTS ||--o{ APV : approvals

entity "document" as DOC {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    level                 : integer   {not null}
    name                  : string    {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    uploadfile_entity_id  : UUID      <<FK>>  {nullable, references uploadfile_entity(id)}
    creator_id            : UUID      <<FK>>  {references user(id)}
    parent_id             : UUID      <<FK>>  {references document(id)}
}
DOC ||--o{ DOC : children
DOC ||--o{ APV : approvals

entity "threat" as THR {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    value                           : float     {not null}
    type                            : CiaType   {not null}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references threat(id)}
}
THR ||--o{ THR : children
THR ||--o{ APV : approvals

entity "vulnerability" as VUL {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    value                           : float     {not null}
    type                            : CiaType   {not null}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references vulnerability(id)}
}
VUL ||--o{ VUL : children
VUL ||--o{ APV : approvals

entity "risk_control" as RSC {
    version_group_id  : string    {not null}
    is_current        : bool      {not null, default: false}
    created_time      : datetime  {not null, default: now() }
    name              : string    {not null}
    description       : string    {not null}
    --
    id                : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    risk_id           : UUID      <<FK>>  {not null, references risk(id)}
    parent_id         : UUID      <<FK>>  {references risk_control(id)}
}
RSC ||--o{ RSC : children
RSC ||--o{ APV : approvals

entity "risk" as RSK {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    value                 : float     {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    asset_id              : UUID      <<FK>>  {not null, references asset(id)}
    threat_id             : UUID      <<FK>>  {not null, references threat(id)}
    vulnerability_id      : UUID      <<FK>>  {not null, references vulnerability(id)}
    parent_id             : UUID      <<FK>>  {references risk(id)}
}
RSK ||--o{ RSK : children
RSK ||--o{ APV : approvals

entity "role" as ROL {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    name                  : string    {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references role(id)}
}
ROL ||--o{ ROL : children
ROL ||--o{ APV : approvals

entity "user" as USR {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    account               : string    {not null}
    username              : string    {not null}
    session_start_time    : datetime  {nullable}
    session_end_time      : datetime  {nullable}
    is_active             : bool      {not null, default: true}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references user(id)}
}
USR ||--o{ USR : children
USR ||--o{ APV : approvals
@enduml
