@startuml
skinparam linetype ortho


entity "asset_setting" as ASTS {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    high_risk                       : float     {not null}
    medium_risk                     : float     {not null}
    low_risk                        : float     {not null}
    calculation_formula             : string    {nullable}
    calculation_formula_description : string    {nullable}
    custom_fields                   : json      {nullable}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references asset_setting(id)}
}
ASTS ||--o{ ASTS : children

' note right of ASTS
'   FK formula_variable.asset_setting_id → asset_setting.id
' end note

entity "formula_variable" as FOV {
    name               : string    {not null}
    description        : string    {not null}
    value              : float     {not null}
    --
    id                 : integer   <<PK>> {not null, autoincrement}
    asset_setting_id   : UUID      <<FK>> {nullable, references asset_setting(id)}
}
ASTS ||--o{ FOV : formula_variable

@enduml
