@startuml
' skinparam linetype ortho

entity "assignment" as ASN {
    description   : string    {not null}
    start_date    : datetime  {not null}
    end_date      : datetime  {not null}
    manager       : string    {not null}
    job_name      : string    {not null}
    created_time  : datetime  {not null}
    id            : integer   <<PK>>  {not null}
}
@enduml
