@startuml
' skinparam linetype ortho
left to right direction

entity "risk" as RSK {
    final_state             : enum risk_processing_state {not null, default: 'unprocessed'} <index>
    treatment_strategy      : enum risk_treatment_strategy {nullable} <index>
    original_value          : float      {not null}
    final_value             : integer    {nullable}
    reduce_value            : integer    {nullable}
    is_trackable            : bool       {not null, default: false}
    tracking_interval_days  : integer    {nullable}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    asset_id                : UUID       <<FK>> {not null, references asset(id)}
    threat_id               : UUID       <<FK>> {not null, references threat(id)}
    vulnerability_id        : UUID       <<FK>> {not null, references vulnerability(id)}
    creator_id              : UUID       <<FK>> {not null, references user(id)}
    parent_id               : UUID       <<FK>> {references risk(id)}
}
RSK ||--o{ RSK : children

entity "asset" as AST {
    name                    : string     {not null}
    description             : text       {not null}
    value                   : float      {not null}
    custom_fields           : json       {nullable}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    parent_id               : UUID       <<FK>> {references asset(id)}
    asset_category_id       : UUID       <<FK>> {not null, references asset_category(id)}
}
AST ||--o{ AST : children
AST ||--o{ RSK : risk

entity "threat" as THR {
    name                    : string     {not null}
    description             : text       {not null}
    value                   : float      {not null}
    type                    : enum CiaType    {not null}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    parent_id               : UUID       <<FK>> {references threat(id)}
}
THR ||--o{ THR : children
THR ||--o{ RSK : risk

entity "vulnerability" as VUL {
    name                    : string     {not null}
    description             : text       {not null}
    value                   : float      {not null}
    type                    : enum CiaType {not null}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    parent_id               : UUID       <<FK>> {references vulnerability(id)}
}
VUL ||--o{ VUL : children
VUL ||--o{ RSK : risk

entity "user" as USR {
    account               : string    {not null}
    username              : string    {not null}
    session_start_time    : datetime  {nullable}
    session_end_time      : datetime  {nullable}
    is_active             : bool      {not null, default: true}
    is_temp               : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    role_id               : UUID      <<FK>>  {not null, references role(id)}
    parent_id             : UUID      <<FK>>  {references user(id)}
}
USR ||--o{ USR : children
USR ||--o{ RSK : risk

entity "risk_control" as RSC {
    name                    : string     {not null}
    description             : text       {not null}
    created_time            : datetime   {not null, default: now() }
    version_group_id        : string     {not null}
    is_current              : bool       {not null, default: false}
    --
    id                      : UUID       <<PK>> {not null, default: uuid_generate_v4()}
    parent_id               : UUID       <<FK>> {references risk_control(id)}
}

RSC ||--o{ RSC : children

entity "risk_risk_control_link" as RRCL {
    --
    risk_id                 : UUID <<PK, FK>> {references risk(id)}
    risk_control_id         : UUID <<PK, FK>> {references risk_control(id)}
}

RSK ||--o{ RRCL
RSC ||--o{ RRCL

@enduml
