@startuml
' skinparam linetype ortho

entity "risk" as RSK {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    value                 : float     {not null}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    asset_id              : UUID      <<FK>>  {not null, references asset(id)}
    threat_id             : UUID      <<FK>>  {not null, references threat(id)}
    vulnerability_id      : UUID      <<FK>>  {not null, references vulnerability(id)}
    parent_id             : UUID      <<FK>>  {references risk(id)}
}
RSK ||--o{ RSK : children

note on link
    FK asset_id → asset.id
    FK threat_id → threat.id
    FK vulnerability_id → vulnerability.id
    FK risk_control_id → risk_control.id
end note

entity "asset" as AST {
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    name                  : string    {not null}
    description           : string    {not null}
    value                 : float     {not null}
    custom_fields         : json      {nullable}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references asset(id)}
    asset_category_id     : UUID      <<FK>>  {not null, references asset_category(id)}
}
AST ||--o{ AST : children
AST ||--o{ RSK : risk

entity "threat" as THR {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    value                           : float     {not null}
    type                            : CiaType   {not null}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references threat(id)}
}
THR ||--o{ THR : children
THR ||--o{ RSK : risk

entity "vulnerability" as VUL {
    version_group_id                : string    {not null}
    is_current                      : bool      {not null, default: false}
    created_time                    : datetime  {not null, default: now() }
    name                            : string    {not null}
    description                     : string    {not null}
    value                           : float     {not null}
    type                            : CiaType   {not null}
    --
    id                              : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id                       : UUID      <<FK>>  {references vulnerability(id)}
}
VUL ||--o{ VUL : children
VUL ||--o{ RSK : risk

entity "risk_control" as RSC {
    version_group_id  : string    {not null}
    is_current        : bool      {not null, default: false}
    created_time      : datetime  {not null, default: now() }
    name              : string    {not null}
    description       : string    {not null}
    --
    id                : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    risk_id           : UUID      <<FK>>  {not null, references risk(id)}
}

RSC ||--o{ RSC : children
RSC ||--o{ RSK : risk
@enduml
