@startuml
' skinparam linetype ortho
left to right direction

entity "user" as USR {
    account               : string    {not null}
    username              : string    {not null}
    session_start_time    : datetime  {nullable}
    session_end_time      : datetime  {nullable}
    is_active             : bool      {not null, default: true}
    is_temp               : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    role_id               : UUID      <<FK>>  {not null, references role(id)}
    parent_id             : UUID      <<FK>>  {references user(id)}
}
USR ||--o{ USR : children

entity "role" as ROL {
    name                  : string    {not null}
    description           : text      {not null}
    is_temp               : bool      {not null, default: false}
    created_time          : datetime  {not null, default: now() }
    version_group_id      : string    {not null}
    is_current            : bool      {not null, default: false}
    --
    id                    : UUID      <<PK>>  {not null, default: uuid_generate_v4()}
    parent_id             : UUID      <<FK>>  {references role(id)}
}
ROL ||--o{ ROL : children
ROL ||--o{ USR : users

entity "permission" as PER {
    id    : integer   <<PK>>  {not null}
    name  : string    {not null}
    path  : string    {not null}
}

entity "role_permission_link" as RPL {
    --
    role_id        : UUID    <<PK, FK>> {references role(id), on delete: CASCADE}
    permission_id  : integer <<PK, FK>> {references permission(id), on delete: CASCADE}
}

ROL ||--o{ RPL : role_permissions
PER ||--o{ RPL : permission_roles

@enduml
