@startuml
title
  Asset Model
  |= 欄位名稱         |= 欄位型態   |= 是否可空 | 主鍵/外來鍵/限制         |= 描述             |
  | id              | UUID        | 否       | PK                      | 資產唯一識別碼    |
  | version_group_id| varchar     | 否       | Not Null                | 資產群組名稱      |
  | is_current      | boolean     | 否       | Not Null, Default       | 是否為目前版本    |
  | created_time    | Datetime    | 否       | Not Null, Default       | 創建時間          |
  | name            | varchar     | 否       | Not Null                | 資產名稱          |
  | description     | varchar     | 否       | Not Null                | 資產描述          |
  | value           | float       | 否       | Not Null                | 資產價值          |
  | custom_fields   | JSONB       | 是       |                          | 自定義欄位        |
  | asset_category_id | UUID      | 否       | FK → asset_category     | 資產所屬分類 ID   |
  | parent_id       | UUID        | 是       | FK → asset              | 父資產的識別碼    |
end title
@enduml
