@startuml
title
  FormulaVariable Model
  |= 欄位名稱           |= 欄位型態   |= 是否可空 | 主鍵/外來鍵/限制       |= 描述              |
  | id                  | integer     | 否       | PK, AutoIncrement      | 變數編號           |
  | name                | varchar     | 否       | Not Null              | 變數名稱           |
  | description         | varchar     | 否       | Not Null              | 變數描述           |
  | value               | float       | 否       | Not Null              | 變數值             |
  | asset_setting_id    | UUID        | 是       | FK → asset_setting    | 所屬 AssetSetting  |
end title
@enduml
