@startuml
title
  Risk Model
  |= 欄位名稱          |= 欄位型態   |= 是否可空 | 主鍵/外來鍵/限制          |= 描述                |
  | id                | UUID        | 否       | PK                       | 風險唯一識別碼       |
  | version_group_id  | varchar     | 否       | Not Null                 | 群組名稱             |
  | is_current        | boolean     | 否       | Not Null, Default        | 是否目前版本         |
  | created_time      | Datetime    | 否       | Not Null, Default        | 創建時間             |
  | value             | float       | 否       | Not Null                 | 風險值               |
  | asset_id          | UUID        | 否       | FK → asset               | 所屬資產 ID          |
  | threat_id         | UUID        | 否       | FK → threat              | 所屬威脅 ID          |
  | vulnerability_id  | UUID        | 否       | FK → vulnerability       | 所屬弱點 ID          |
  | parent_id         | UUID        | 是       | FK → risk                | 父風險 ID            |
end title
@enduml
