@startuml
title 稽核一覽表
start

:載入稽核一覽表頁面;

:顯示欄位資料
(稽核標題、描述、狀態、佐證資料數量、建立時間);

partition "使用者互動" {

    if (使用者輸入搜尋關鍵字?) then (是)
        :過濾稽核清單;
    endif

    if (使用者切換頁碼或筆數?) then (是)
        :更新分頁/每頁顯示行數;
    endif

    :檢視稽核詳情或進入編輯頁;
}

stop
@enduml
