@startuml
title 工作派工一覽表
start

:載入工作派工一覽表頁面;

:顯示欄位資料
(派工名稱、建立人員、關聯類別/ID、建立時間、操作);

partition "使用者互動" {

    if (使用者輸入搜尋關鍵字?) then (是)
        :過濾派工紀錄清單;
    endif

    if (使用者選擇每頁顯示行數?) then (是)
        :更新顯示行數設定;
    endif

    :檢視派工紀錄詳情;
    :查看各處理人員狀態、進度與附件連結;
}

stop
@enduml
