@startuml

left to right direction

actor 使用者

package "威脅一覽表" {
    usecase "顯示威脅列表" as UC1
    usecase "檢視欄位（ID、名稱、類型、數值、描述、狀態）" as UC2
    usecase "設定每頁顯示筆數" as UC3
}

package "修改威脅" {
    usecase "顯示威脅列表" as UC4
    usecase "編輯威脅資料" as UC5
    usecase "刪除威脅資料" as UC6
    usecase "＋新增威脅" as UC7
    usecase "＋匯入威脅" as UC8
    usecase "自動記錄建立時間" as UC9
}

UC5 .down.> UC9 : <<include>>
UC7 .down.> UC9 : <<include>>
UC8 .down.> UC9 : <<include>>

使用者 --> UC1
使用者 --> UC2
使用者 --> UC3
使用者 --> UC4
使用者 --> UC5
使用者 --> UC6
使用者 --> UC7
使用者 --> UC8

@enduml
